testing

diff --git a/.github/workflows/path-to-transitivity.yml b/.github/workflows/path-to-transitivity.yml
--- a/.github/workflows/path-to-transitivity.yml
+++ b/.github/workflows/path-to-transitivity.yml
@@ -106,13 +106,14 @@ jobs:
               sbom_content=$(jq -c '.' "$dirname/${bom_filename}.json")
 
               echo "Uploading ${bom_filename}.json"
-              response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Authorization: Bearer $SEMGREP_APP_TOKEN" -H "Content-Type: application/json" \
-                -d "{\"repository_name\":\"$REPO_NAME\", \"commit_hash\":\"$COMMIT_HASH\", \"manifest_path\":\"$filepath\", \"sbom\": $sbom_content}" \
-                $SEMGREP_APP_URL/api/sca/dependencies/upload_dep_sboms)
-              if [ "$response" -ne 200 ]; then
-                echo "Failed to upload ${bom_filename}.json, received response code $response"
-                exit 1
-              fi
+              echo $sbom_content
+              # response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Authorization: Bearer $SEMGREP_APP_TOKEN" -H "Content-Type: application/json" \
+              #   -d "{\"repository_name\":\"$REPO_NAME\", \"commit_hash\":\"$COMMIT_HASH\", \"manifest_path\":\"$filepath\", \"sbom\": $sbom_content}" \
+              #   $SEMGREP_APP_URL/api/sca/dependencies/upload_dep_sboms)
+              # if [ "$response" -ne 200 ]; then
+              #   echo "Failed to upload ${bom_filename}.json, received response code $response"
+              #   exit 1
+              # fi
             ' sh {} \;
           }
 
